### ISSUE TITLE
Constant JSONDecodeError exceptions

### ISSUE THREAD

**Issue by tySwift93** [pavoni/pyvera#53]
I use pyvera in my instance of Home Assistant (HA). I have consistently noticed that sometime between one and two days after starting HA, pyvera's subscription/polling feature stops working due to a single JSONDecodeError exception. I have created a pull request (https://github.com/pavoni/pyvera/pull/52) that will safely handle JSONDecodeError exceptions and allow polling to continue.

For reference, the stack trace always looks like this:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pyvera/subscribe.py", line 118, in _run_poll_server
    controller.get_changed_devices(timestamp))
  File "/usr/local/lib/python3.5/site-packages/pyvera/__init__.py", line 218, in get_changed_devices
    result = self.data_request(payload, TIMEOUT*2).json()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The pull request works perfectly for me, and should hopefully help out anyone else who may or may not be experiencing this problem.

**Comment by tySwift93** [comment]
Issue fixed in merge request https://github.com/pavoni/pyvera/pull/52
