### ISSUE TITLE
Netatmo Thermostat issue

### ISSUE THREAD

**Issue by dpembo** [pavoni/pyvera#65]
I get a pyvera error whilst it's trying to figure out my netatmo thermostat that has been added to vera.

Error is:
```

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 245, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/climate/__init__.py", line 417, in state_attributes
    self._convert_for_display(self.current_temperature),
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/climate/vera.py", line 112, in current_temperature
    return self.vera_device.get_current_temperature()
  File "/root/.homeassistant/deps/pyvera/__init__.py", line 841, in get_current_temperature
    return float(self.get_value('temperature'))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

Thermostat xml from vera looks like:
`&lt;device name="my thermostat" altid="" id="169" category="5" subcategory="-1" room="0" parent="0" ip="xxx.xxx.xxx.xxx" currentTemperature="22.2" batterylevel="100"/&gt;`

**Comment by alanfischer** [comment]
This should be resolved with the latest pyvera, and the HA PR to update that is here: https://github.com/home-assistant/home-assistant/pull/8437

Once that goes in this should be resolved.

**Comment by alanfischer** [comment]
Closing this issue since it should be resolved.
