### ISSUE TITLE
IndexError in get_color

### ISSUE THREAD

**Issue by alanfischer** [pavoni/pyvera#67]
Here is the stack trace as reported here: https://github.com/home-assistant/home-assistant/issues/8526

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyvera/subscribe.py", line 129, in _run_poll_server
    self._event(device_data)
  File "/usr/local/lib/python3.6/site-packages/pyvera/subscribe.py", line 59, in _event
    self._event_device(device, device_data)
  File "/usr/local/lib/python3.6/site-packages/pyvera/subscribe.py", line 96, in _event_device
    callback(device)
  File "/usr/src/app/homeassistant/components/vera.py", line 147, in _update_callback
    self.update()
  File "/usr/src/app/homeassistant/components/light/vera.py", line 85, in update
    self._color = self.vera_device.get_color()
  File "/usr/local/lib/python3.6/site-packages/pyvera/__init__.py", line 660, in get_color
    val = [cur.split(',')[c] for c in ci]
  File "/usr/local/lib/python3.6/site-packages/pyvera/__init__.py", line 660, in <listcomp>
    val = [cur.split(',')[c] for c in ci]
IndexError: list index out of range
```

I'm not sure what's getting returned by CurrentColor that isn't in get_color_index.  Do we try to understand exactly whats going on or just wrap 660 & 661 to catch IndexErrors?

```
try:
    val = [cur.split(',')[c] for c in ci]
    return [int(v.split('=')[1]) for v in val]
except IndexError:
    return None
```

**Comment by pavoni** [comment]
Happy with either - but catching the exception  makes sense to me

**Comment by alanfischer** [comment]
PR here: https://github.com/pavoni/pyvera/pull/68
